// Code generated by gen-fhir-types. DO NOT EDIT.

// gen-fhir-types generates Go structs from a FHIR R5 JSON Schema file.
//
// Usage:
//
//	gen-fhir-types --schema fhir.schema.json --output core/fhir/r5/types.go --package r5
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
	"text/template"
	"unicode"
)

// fhirSchema is the top-level structure of a FHIR R5 JSON Schema file.
type fhirSchema struct {
	Definitions map[string]fhirDefinition `json:"definitions"`
}

// fhirDefinition represents a single FHIR type or resource definition.
type fhirDefinition struct {
	Description string                    `json:"description"`
	Properties  map[string]fhirProperty   `json:"properties"`
	Required    []string                  `json:"required"`
	Enum        []string                  `json:"enum"`
	Type        string                    `json:"type"`
}

// fhirProperty represents a single property within a FHIR definition.
type fhirProperty struct {
	Description string          `json:"description"`
	Type        string          `json:"type"`
	Ref         string          `json:"$ref"`
	Items       *fhirProperty   `json:"items"`
	Enum        []string        `json:"enum"`
	AdditionalProperties *fhirProperty `json:"additionalProperties"`
}

// goField is a resolved Go struct field ready for template rendering.
type goField struct {
	Name     string
	Type     string
	JSONTag  string
	Comment  string
	Required bool
}

// goStruct is a resolved Go struct ready for template rendering.
type goStruct struct {
	Name    string
	Comment string
	Fields  []goField
}

const fileTemplate = `// Code generated by gen-fhir-types. DO NOT EDIT.

package {{.Package}}

// Reference represents a FHIR R5 Reference type.
// It holds a relative or absolute URL to another resource.
type Reference struct {
	Reference  *string ` + "`" + `json:"reference,omitempty"` + "`" + `
	Type       *string ` + "`" + `json:"type,omitempty"` + "`" + `
	Display    *string ` + "`" + `json:"display,omitempty"` + "`" + `
	Identifier *Identifier ` + "`" + `json:"identifier,omitempty"` + "`" + `
}

{{range .Structs}}
{{- if .Comment}}// {{.Comment}}
{{end -}}
type {{.Name}} struct {
{{- range .Fields}}
{{- if .Comment}}
	// {{.Comment}}{{end}}
	{{.Name}} {{.Type}} ` + "`" + `json:"{{.JSONTag}}"` + "`" + `
{{- end}}
}
{{end}}
`

// templateData is passed to the file template.
type templateData struct {
	Package string
	Structs []goStruct
}

func main() {
	schemaPath := flag.String("schema", "fhir.schema.json", "Path to the FHIR R5 JSON schema file")
	outputPath := flag.String("output", "core/fhir/r5/types.go", "Path to the output Go file")
	pkgName := flag.String("package", "r5", "Go package name for the generated file")
	flag.Parse()

	data, err := os.ReadFile(*schemaPath)
	if err != nil {
		log.Fatalf("gen-fhir-types: reading schema: %v", err)
	}

	var schema fhirSchema
	if err := json.Unmarshal(data, &schema); err != nil {
		log.Fatalf("gen-fhir-types: parsing schema: %v", err)
	}

	structs := generateStructs(schema)

	tmpl, err := template.New("fhir").Parse(fileTemplate)
	if err != nil {
		log.Fatalf("gen-fhir-types: parsing template: %v", err)
	}

	out, err := os.Create(*outputPath)
	if err != nil {
		log.Fatalf("gen-fhir-types: creating output file: %v", err)
	}
	defer out.Close()

	td := templateData{
		Package: *pkgName,
		Structs: structs,
	}
	if err := tmpl.Execute(out, td); err != nil {
		log.Fatalf("gen-fhir-types: rendering template: %v", err)
	}

	fmt.Printf("gen-fhir-types: wrote %d structs to %s\n", len(structs), *outputPath)
}

// generateStructs converts a parsed FHIR schema into a sorted slice of goStructs.
func generateStructs(schema fhirSchema) []goStruct {
	// Collect and sort definition names for deterministic output.
	names := make([]string, 0, len(schema.Definitions))
	for name := range schema.Definitions {
		names = append(names, name)
	}
	sort.Strings(names)

	seen := map[string]bool{"Reference": true, "Identifier": true}
	var structs []goStruct

	for _, name := range names {
		def := schema.Definitions[name]
		// Skip primitive type aliases and pure enum types with no properties.
		if len(def.Properties) == 0 {
			continue
		}
		goName := sanitizeName(name)
		if seen[goName] {
			continue
		}
		seen[goName] = true

		gs := buildStruct(goName, def)
		structs = append(structs, gs)
	}
	return structs
}

// buildStruct converts a single FHIR definition into a goStruct.
func buildStruct(name string, def fhirDefinition) goStruct {
	requiredSet := make(map[string]bool, len(def.Required))
	for _, r := range def.Required {
		requiredSet[r] = true
	}

	// Sort property names for deterministic output.
	propNames := make([]string, 0, len(def.Properties))
	for p := range def.Properties {
		propNames = append(propNames, p)
	}
	sort.Strings(propNames)

	fields := make([]goField, 0, len(propNames))
	for _, propName := range propNames {
		prop := def.Properties[propName]
		required := requiredSet[propName]

		goType, comment := resolveType(prop, required)
		jsonTag := propName
		if !required {
			jsonTag += ",omitempty"
		}

		// Pointer-wrap optional non-slice, non-map types for clean omitempty semantics.
		if !required && !strings.HasPrefix(goType, "[]") && !strings.HasPrefix(goType, "map[") && !strings.HasPrefix(goType, "*") {
			goType = "*" + goType
		}

		fields = append(fields, goField{
			Name:     sanitizeName(propName),
			Type:     goType,
			JSONTag:  jsonTag,
			Comment:  comment,
			Required: required,
		})
	}

	comment := def.Description
	if len(comment) > 120 {
		comment = comment[:117] + "..."
	}

	return goStruct{
		Name:    name,
		Comment: comment,
		Fields:  fields,
	}
}

// resolveType maps a FHIR property to a Go type string and an optional field comment.
func resolveType(prop fhirProperty, required bool) (string, string) {
	// $ref takes precedence.
	if prop.Ref != "" {
		return resolveRef(prop.Ref), ""
	}

	switch prop.Type {
	case "string":
		return resolveStringFormat(prop)
	case "number":
		return "float64", ""
	case "integer":
		return "int64", ""
	case "boolean":
		return "bool", ""
	case "array":
		if prop.Items == nil {
			return "[]interface{}", ""
		}
		itemType, comment := resolveType(*prop.Items, true)
		return "[]" + itemType, comment
	case "object":
		if prop.AdditionalProperties != nil {
			valType, _ := resolveType(*prop.AdditionalProperties, true)
			return "map[string]" + valType, ""
		}
		return "map[string]interface{}", ""
	default:
		return "interface{}", ""
	}
}

// resolveStringFormat applies FHIR-specific string format overrides.
func resolveStringFormat(prop fhirProperty) (string, string) {
	desc := strings.ToLower(prop.Description)
	switch {
	case strings.Contains(desc, "datetime") || strings.Contains(desc, "date-time") || strings.Contains(desc, "date and time"):
		// Use string for FHIR dateTime; consider time.Time in real parsing code.
		return "string", "FHIR dateTime — consider time.Time for real parsing"
	case strings.Contains(desc, "decimal"):
		return "float64", "FHIR decimal mapped to float64"
	default:
		return "string", ""
	}
}

// resolveRef converts a JSON Schema $ref like "#/definitions/Patient" to a Go type name.
func resolveRef(ref string) string {
	// Handle FHIR reference type specially.
	if strings.EqualFold(ref, "#/definitions/Reference") || strings.HasSuffix(ref, "/Reference") {
		return "Reference"
	}
	parts := strings.Split(ref, "/")
	raw := parts[len(parts)-1]
	return sanitizeName(raw)
}

// sanitizeName converts a FHIR definition name to a valid, exported Go identifier.
func sanitizeName(name string) string {
	// Replace disallowed characters with underscores.
	var b strings.Builder
	firstChar := true
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			if firstChar && unicode.IsDigit(r) {
				b.WriteRune('_')
			}
			if firstChar {
				b.WriteRune(unicode.ToUpper(r))
				firstChar = false
			} else {
				b.WriteRune(r)
			}
		} else {
			if !firstChar {
				b.WriteRune('_')
			}
		}
	}
	s := b.String()
	// Trim trailing underscores.
	s = strings.TrimRight(s, "_")
	if s == "" {
		return "Unknown"
	}
	return s
}
