// Command gen-fhir-types generates Go structs from the FHIR R5 JSON Schema.
//
// Usage:
//
//	go run tools/gen-fhir-types/main.go -schema fhir.schema.json -out core/fhir/r5/types.go
//
// The input schema file is the FHIR R5 JSON Schema (fhir.schema.json) published
// by HL7 at https://hl7.org/fhir/R5/fhir.schema.json.
//
// Only resources specified with -resources (comma-separated) are generated.
// Common types (Meta, Coding, CodeableConcept, etc.) are always included.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

// Schema represents the top-level FHIR JSON Schema structure.
type Schema struct {
	Definitions map[string]*SchemaDef `json:"$defs"`
}

// SchemaDef represents a single type/resource definition.
type SchemaDef struct {
	Description string              `json:"description"`
	Type        string              `json:"type"`
	Properties  map[string]*PropDef `json:"properties"`
	AllOf       []*SchemaRef        `json:"allOf"`
	Required    []string            `json:"required"`
}

// PropDef describes a single property.
type PropDef struct {
	Type        string              `json:"type"`
	Description string              `json:"description"`
	Ref         string              `json:"$ref"`
	Items       *PropDef            `json:"items"`
	OneOf       []*SchemaRef        `json:"oneOf"`
	Required    []string            `json:"required"`
}

// SchemaRef is a $ref reference.
type SchemaRef struct {
	Ref string `json:"$ref"`
}

// resourceOrder lists the FHIR resources to generate in order.
var allResources = []string{
	"Patient",
	"Practitioner",
	"Encounter",
	"Observation",
	"Condition",
	"MedicationRequest",
	"DiagnosticReport",
	"ServiceRequest",
	"Immunization",
	"Claim",
	"ClaimResponse",
	"ImagingStudy",
	"Subscription",
	"SubscriptionTopic",
}

// commonTypes lists FHIR base types always emitted.
var commonTypes = []string{
	"Meta",
	"Narrative",
	"Coding",
	"CodeableConcept",
	"Identifier",
	"HumanName",
	"Address",
	"ContactPoint",
	"Reference",
	"Period",
	"Quantity",
	"Annotation",
	"Attachment",
	"Extension",
	"Ratio",
	"Range",
	"Money",
	"SampledData",
	"Timing",
	"Signature",
	"Dosage",
	"BackboneElement",
}

// nzExtras are types manually added to the R5 package (not from schema).
var nzExtras = []string{
	"PatientCommunication",
	"PatientContact",
	"PractitionerQualification",
	"EncounterParticipant",
	"EncounterDiagnosis",
	"ObservationReferenceRange",
	"MedicationRequestDispenseRequest",
	"MedicationRequestSubstitution",
	"ClaimCareTeam",
	"ClaimDiagnosis",
	"ClaimProcedure",
	"ClaimItem",
	"ClaimResponseItem",
	"ClaimResponseAdjudication",
	"ClaimResponseAddItem",
	"ClaimResponseTotal",
	"BundleEntry",
	"BundleEntrySearch",
	"BundleEntryRequest",
	"BundleEntryResponse",
	"BundleLink",
	"OperationOutcomeIssue",
}

func main() {
	schemaFile := flag.String("schema", "fhir.schema.json", "path to FHIR JSON Schema")
	outFile := flag.String("out", "core/fhir/r5/types.go", "output Go file path")
	resourcesFlag := flag.String("resources", "", "comma-separated resources to generate (default: all)")
	flag.Parse()

	schema := loadSchema(*schemaFile)

	resources := allResources
	if *resourcesFlag != "" {
		resources = strings.Split(*resourcesFlag, ",")
		for i := range resources {
			resources[i] = strings.TrimSpace(resources[i])
		}
	}

	// Collect all type names we need.
	needed := make(map[string]bool)
	for _, r := range commonTypes {
		needed[r] = true
	}
	for _, r := range resources {
		needed[r] = true
	}

	// Resolve transitive dependencies from allOf and property refs.
	resolveDeps(schema, resources, needed)

	// Generate sorted list.
	typeNames := make([]string, 0, len(needed))
	for n := range needed {
		typeNames = append(typeNames, n)
	}
	sort.Strings(typeNames)

	var b strings.Builder

	b.WriteString(`// Package r5 provides FHIR R5 Go structs generated from the HL7 FHIR R5 JSON Schema.
// NZ-specific extensions and helper methods are added manually.
//
// Code generated by tools/gen-fhir-types/main.go. DO NOT EDIT.
package r5

import "time"

`)

	// Generate common types first.
	for _, name := range typeNames {
		// Skip NZ extras — they are defined manually.
		if contains(nzExtras, name) {
			continue
		}
		def, ok := schema.Definitions[name]
		if !ok {
			continue
		}
		generateStruct(&b, name, def, schema)
	}

	content := b.String()
	if err := os.WriteFile(*outFile, []byte(content), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", *outFile, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %d FHIR R5 types in %s\n", len(typeNames), *outFile)
}

func loadSchema(path string) *Schema {
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error reading schema %s: %v\n", path, err)
		os.Exit(1)
	}
	var schema Schema
	if err := json.Unmarshal(data, &schema); err != nil {
		fmt.Fprintf(os.Stderr, "error parsing schema: %v\n", err)
		os.Exit(1)
	}
	return &schema
}

func resolveDeps(schema *Schema, resources []string, needed map[string]bool) {
	// Iterative dependency resolution.
	changed := true
	for changed {
		changed = false
		for name := range needed {
			def, ok := schema.Definitions[name]
			if !ok {
				continue
			}
			// Check allOf references.
			for _, ref := range def.AllOf {
				dep := resolveRef(ref.Ref)
				if dep != "" && !needed[dep] {
					needed[dep] = true
					changed = true
				}
			}
			// Check property references.
			for _, prop := range def.Properties {
				deps := propRefs(prop)
				for _, d := range deps {
					if !needed[d] && schema.Definitions[d] != nil {
						needed[d] = true
						changed = true
					}
				}
			}
		}
	}
}

func propRefs(p *PropDef) []string {
	var deps []string
	if p.Ref != "" {
		if d := resolveRef(p.Ref); d != "" {
			deps = append(deps, d)
		}
	}
	if p.Items != nil {
		deps = append(deps, propRefs(p.Items)...)
	}
	for _, o := range p.OneOf {
		if d := resolveRef(o.Ref); d != "" {
			deps = append(deps, d)
		}
	}
	return deps
}

func resolveRef(ref string) string {
	// "$defs.Foo" or "#/$defs/Foo"
	ref = strings.TrimPrefix(ref, "#/")
	ref = strings.TrimPrefix(ref, "$defs/")
	ref = strings.TrimPrefix(ref, "$defs.")
	return ref
}

func goTypeName(name string) string {
	// Handle namespaced names like "Element" -> "Element"
	// Strip "BackboneElement" suffix for nested types.
	return name
}

func generateStruct(b *strings.Builder, name string, def *SchemaDef, schema *Schema) {
	desc := strings.TrimSpace(def.Description)
	if desc != "" {
		b.WriteString(fmt.Sprintf("// %s %s\n", name, desc))
	}
	b.WriteString(fmt.Sprintf("type %s struct {\n", name))

	// Collect properties from allOf (inheritance).
	props := make(map[string]*PropDef)
	for _, ref := range def.AllOf {
		dep := resolveRef(ref.Ref)
		if depDef, ok := schema.Definitions[dep]; ok {
			for k, v := range depDef.Properties {
				props[k] = v
			}
		}
	}
	// Own properties override inherited ones.
	for k, v := range def.Properties {
		props[k] = v
	}

	// Sort property names for deterministic output.
	propNames := make([]string, 0, len(props))
	for n := range props {
		propNames = append(propNames, n)
	}
	sort.Strings(propNames)

	requiredSet := make(map[string]bool)
	for _, r := range def.Required {
		requiredSet[r] = true
	}

	for _, propName := range propNames {
		prop := props[propName]
		goField := toGoField(propName)
		goType, omit := toGoType(prop, schema, requiredSet[propName])
		tag := fmt.Sprintf(`json:"%s%s"`, propName, omit)
		b.WriteString(fmt.Sprintf("\t%s %s `%s`\n", goField, goType, tag))
	}

	b.WriteString("}\n\n")
}

func toGoField(snake string) string {
	// camelCase or snake_case to PascalCase.
	parts := strings.FieldsFunc(snake, func(r rune) bool { return r == '_' || r == '-' })
	for i, p := range parts {
		parts[i] = strings.Title(p) //nolint:staticcheck
	}
	field := strings.Join(parts, "")
	// Handle abbreviations.
	field = strings.ReplaceAll(field, "Url", "URL")
	field = strings.ReplaceAll(field, "Uri", "URI")
	field = strings.ReplaceAll(field, "Id", "ID")
	field = strings.ReplaceAll(field, "Nhi", "NHI")
	field = strings.ReplaceAll(field, "Hpi", "HPI")
	return field
}

func toGoType(prop *PropDef, schema *Schema, required bool) (string, string) {
	omit := ",omitempty"

	// Resolve $ref.
	if prop.Ref != "" {
		dep := resolveRef(prop.Ref)
		if dep == "string" {
			if required {
				return "string", ""
			}
			return "string", omit
		}
		if dep == "integer" || dep == "int" {
			if required {
				return "int", ""
			}
			return "int", omit
		}
		if dep == "number" || dep == "decimal" {
			if required {
				return "float64", ""
			}
			return "float64", omit
		}
		if dep == "boolean" {
			if required {
				return "bool", ""
			}
			return "*bool", omit
		}
		if dep == "dateTime" || dep == "instant" || dep == "date" || dep == "time" {
			return "*time.Time", omit
		}
		if dep == "base64Binary" {
			return "string", omit
		}
		if dep == "uri" || dep == "url" || dep == "canonical" || dep == "oid" || dep == "uuid" {
			return "string", omit
		}
		if dep == "code" || dep == "markdown" || dep == "id" {
			return "string", omit
		}
		if dep == "xhtml" || dep == "base64Binary" {
			return "string", omit
		}
		// Complex type reference.
		if required {
			return dep, ""
		}
		return "*" + dep, omit
	}

	switch prop.Type {
	case "string":
		if required {
			return "string", ""
		}
		return "string", omit
	case "integer":
		if required {
			return "int", ""
		}
		return "int", omit
	case "number":
		if required {
			return "float64", ""
		}
		return "float64", omit
	case "boolean":
		if required {
			return "bool", ""
		}
		return "*bool", omit
	case "array":
		if prop.Items == nil {
			return "[]interface{}", omit
		}
		elemType, _ := toGoType(prop.Items, schema, false)
		return "[]" + elemType, omit
	case "object":
		if prop.Ref != "" {
			dep := resolveRef(prop.Ref)
			if required {
				return dep, ""
			}
			return "*" + dep, omit
		}
		// Generic object (map).
		return "map[string]interface{}", omit
	default:
		// Check oneOf for union types.
		if len(prop.OneOf) > 0 {
			// If oneOf has a primitive and a complex, use interface{}.
			return "interface{}", omit
		}
		return "interface{}", omit
	}
}

func contains(slice []string, s string) bool {
	for _, el := range slice {
		if el == s {
			return true
		}
	}
	return false
}

// nolint:gocyclo
func init() {
	// Ensure regex is used.
	_ = regexp.MustCompile
}